export const TYPES = {
	SET_ACTIVE_COLOR: 'SET_ACTIVE_COLOR',
	SET_COLOR: 'SET_COLOR',
	SET_PRIMARY_COLOR: 'SET_PRIMARY_COLOR',
	SET_SECOND_COLOR: 'SET_SECOND_COLOR',
	SET_ACTIVE_TOOL: 'SET_ACTIVE_TOOL',
	SET_SIZE_STROKE_TOOL: 'SET_SIZE_STROKE_TOOL',
	SET_ACTIVE_STROKE_TOOL: 'SET_SIZE_STROKE_TOOL',
	SET_ACTIVE_FILL_TOOL: 'SET_SIZE_STROKE_TOOL',
}